### Deleting user
DELETE https://api.nm.213-109-192-92.nip.io/api/extclients/vpn/T
Authorization: Bearer BBMfxj2OCTdXbTAiFb3fXIOIjyvuu5

### Creating user w/out response
POST https://api.nm.213-109-192-92.nip.io/api/extclients/vpn/b0236f55-869a-4836-b01f-aeed1f910915
Authorization: Bearer BBMfxj2OCTdXbTAiFb3fXIOIjyvuu5

### List of users
GET https://api.nm.213-109-192-92.nip.io/api/extclients
Authorization: Bearer BBMfxj2OCTdXbTAiFb3fXIOIjyvuu5
Accept: application/json, text/plain, */*

### Changing user's fields
PUT https://api.nm.213-109-192-92.nip.io/api/extclients/vpn/billy-herrington
Authorization: Bearer BBMfxj2OCTdXbTAiFb3fXIOIjyvuu5
Content-Type: application/json

{
  "clientid": "billy-herrington",
  "enabled": true
}


### Getting user's configuration
GET https://api.nm.213-109-192-92.nip.io/api/extclients/vpn/mega-cyborg/file
Authorization: Bearer BBMfxj2OCTdXbTAiFb3fXIOIjyvuu5
